### ISSUE TITLE
katalog .idea do gitignore

### ISSUE THREAD

**Issue by nexik** [miloszszymonek/html#11]
nalezy usunac najpierw ten katalog, potem zcommitowac
nastepnie dodac do gitignore, potem zcommitowac

**Comment by miloszszymonek** [comment]
https://github.com/miloszszymonek/html/commit/928006bab92c73ae6515ebaccb2a9a7d14e46200
https://github.com/miloszszymonek/html/commit/1338ea0bb5c88119f2380a3f67fafbc0095a1716
