### ISSUE TITLE
usunac nadmiarowe assety z katalogu src

### ISSUE THREAD

**Issue by nexik** [miloszszymonek/html#8]
katalogi:

[] js
[] fonts
[] css

oraz plik 

style.csss

**Comment by miloszszymonek** [comment]
deleted

**Comment by nexik** [comment]
te katalogi nadal sa tam gdzie byly

**Comment by miloszszymonek** [comment]
https://github.com/miloszszymonek/html/commit/e1b1230cf8da302f01b6a1db37f254329126b84e
