### ISSUE TITLE
uzycie wzglednej sciezki do composera

### ISSUE THREAD

**Issue by nexik** [miloszszymonek/html#9]
aktualnie jest uzywane

`require_once '/var/www/vendor/autoload.php';`

nie kazdy bedzie mial to w katalogu /var/www tak wiec nalezy uzyc sciezki wzglednej

http://lmgtfy.com/?q=relative+path+linux

**Comment by miloszszymonek** [comment]
https://github.com/miloszszymonek/html/commit/b0efd13d503450a33b334ac9e4b5066fd461cb1a
